  import type { Metadata } from "next";
  import { Geist, Geist_Mono, Nanum_Myeongjo, Albert_Sans } from "next/font/google";
  import "./globals.css";

  // Nanum Myeongjo (main font)
  const nanum = Nanum_Myeongjo({
    variable: "--font-nanum",
    weight: ["400", "700"],
    subsets: ["latin"],
  });

  // Albert Sans (secondary)
  const albert = Albert_Sans({
    variable: "--font-albert",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body
          className={`${nanum.variable} ${albert.variable} bg-white`}
        >
          {children}
        </body>
      </html>
    );
  }
